In [1]:
# First we will study some numpy topics which we've left for later.

# Stacking (Merging Arrays) Vstack, Hstack

In [2]:
import numpy as np

In [5]:
# First do some experiments with 1d arrays only.

a = np.arange(1,5)
b = np.arange(1,5)

np.hstack((a,b))


array([1, 2, 3, 4, 1, 2, 3, 4])

In [6]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
# Now 2d matrix with only one rows

a = np.arange(1,5).reshape((1,4))
b = np.arange(1,5).reshape((1,4))

np.vstack((a,b))
 

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [8]:
np.hstack((a,b))

array([[1, 2, 3, 4, 1, 2, 3, 4]])

In [9]:
# Now some experiments with 2d with multiple rows

a = np.arange(1,13).reshape((3,4))
b = np.arange(1,13).reshape((3,4))

np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [13]:
# in this case only vstack will work

a = np.arange(1,13).reshape((3,4))
b =  np.arange(1,5).reshape((1,4))

np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [14]:
# In this case only hstack will work

a = np.arange(1,13).reshape((4,3))
b = np.arange(1,5).reshape((4,1))

np.hstack((a,b))

array([[ 1,  2,  3,  1],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  3],
       [10, 11, 12,  4]])

## Tiling (np.tile)

In [16]:
# It replicates the array in the form of tiles based on the parameter we provide.

a = np.arange(1,13).reshape((3,4))

np.tile(a,(3,2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [17]:
a = np.arange(1,13).reshape((3,4))

np.tile(a,(4,5))

array([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,
         1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,
         5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,
         9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,
         1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,
         5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,
         9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,
         1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,
         5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,
         9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,
         1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6

# Pandas Practice

In [18]:
!pip install pandas

     ---------------------------------------- 10.6/10.6 MB 4.8 MB/s eta 0:00:00
     -------------------------------------- 341.8/341.8 kB 4.3 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
# why pandas?
# Pandas is most commonly used library in the world of data science.
# Pandas is heterogeneous in nature. So it will be helpful when we have different data types.
# It is helpful to work with data which is in tabular form 

In [20]:
import pandas as pd

In [22]:
!gdown 1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_

Downloading...
From: https://drive.google.com/uc?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
To: C:\Users\htc\mckinsey.csv

  0%|          | 0.00/83.8k [00:00<?, ?B/s]
100%|##########| 83.8k/83.8k [00:00<00:00, 1.56MB/s]


In [23]:
df = pd.read_csv("C:/Users/htc/mckinsey.csv")

In [24]:
df

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [34]:
# Wow Pandas is so magical It is providing us so many things automatically.
# Headers, Shape of the dataframe, Indices

In [35]:
# In pandas when we have a dataset in the form of tabular data. Then we call it dataframe
type(df)

pandas.core.frame.DataFrame

# 2 ways to access any particular columns

In [36]:
# 1st approach is most frequently used and recommended to use.
# When pandas sees a particular column to be in string format, it automatically assumes it to be a object dtype
# In pandas whenever we are accessing a column. Pandas returns us a series(column + indices).

df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [37]:
type(df['country'])

pandas.core.series.Series

In [38]:
# More functions we will study noe
# df.info()
# df.describe()
# df.head()
# df.tail()

In [41]:
# This function giving us so many information already. 
# Columns, dtypes, shape, Null Counts, frequency of dtypes, memory usage etc.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [45]:
# This function is calculating so many things for us already.
# count, mean, standard deviation, min, max, percentile, median etc.
# But this function doesn't return the columns which have string dtypes.
# so we will try to take all the columns using a parameter include = all

df.describe()

year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [47]:
# returning so many NaN values because it doesn't make any sense to calculate mean for a str of a 'country'. .

df.describe(include = 'all')

country        year    population continent     life_exp  \
count          1704  1704.00000  1.704000e+03      1704  1704.000000   
unique          142         NaN           NaN         5          NaN   
top     Afghanistan         NaN           NaN    Africa          NaN   
freq             12         NaN           NaN       624          NaN   
mean            NaN  1979.50000  2.960121e+07       NaN    59.474439   
std             NaN    17.26533  1.061579e+08       NaN    12.917107   
min             NaN  1952.00000  6.001100e+04       NaN    23.599000   
25%             NaN  1965.75000  2.793664e+06       NaN    48.198000   
50%             NaN  1979.50000  7.023596e+06       NaN    60.712500   
75%             NaN  1993.25000  1.958522e+07       NaN    70.845500   
max             NaN  2007.00000  1.318683e+09       NaN    82.603000   

              gdp_cap  
count     1704.000000  
unique            NaN  
top               NaN  
freq              NaN  
mean      7215.327081  
std       9857.454543  
min        241.165876  
25%       1202.060309  
50%       3531.846988  
75%       9325.462346  
max     113523.132900

In [49]:
# This function automatically returns us the top 5 rows.
# However if you wish to get more or less rows just provide the no. in parameter. df.head(10)

df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [51]:
df.head(10)

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360
6  Afghanistan  1982    12881816      Asia    39.854  978.011439
7  Afghanistan  1987    13867957      Asia    40.822  852.395945
8  Afghanistan  1992    16317921      Asia    41.674  649.341395
9  Afghanistan  1997    22227415      Asia    41.763  635.341351

In [53]:
# This function automatically returns us the bottom 5 rows.
# However if you wish to get more or less rows just provide the no. in parameter. df.tail(10)


df.tail()

country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [54]:
df.tail(3)

country  year  population continent  life_exp     gdp_cap
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

# How to  create our own data frames. 2 Approaches
## 1). Row oriented
## 2.) Column oriented

In [56]:
# ROW ORIENTED APPROACH

df1 = pd.DataFrame([['Zimbabwe',1997,11404948,'Africa',46.809,792.449960],
                    ['Zimbabwe',2002,11926563,'Africa',39.989,672.038623],
                   ['Zimbabwe',2007,12311143,'Africa',43.487,469.709298]],
                   columns = ['country','year','population','continent','life_exp','gdp_cap'])

In [57]:
df1

country  year  population continent  life_exp     gdp_cap
0  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1  Zimbabwe  2002    11926563    Africa    39.989  672.038623
2  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [58]:
# COLUMN ORIENTED APPROACH

df2 = pd.DataFrame({'country':['Zimbabwe','Zimbabwe','Zimbabwe'],
                   'year':[1997,2002,2007],
                   'population':[11404948,11926563,12311143],
                   'continent':['Africa','Africa','Africa'],
                   'life_exp':[46.809,39.989,43.487],
                   'gdp_cap':[792.449960,672.038623,469.709298]})

In [59]:
df2

country  year  population continent  life_exp     gdp_cap
0  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1  Zimbabwe  2002    11926563    Africa    39.989  672.038623
2  Zimbabwe  2007    12311143    Africa    43.487  469.709298

# Basic operation on columns

In [60]:
# different ways of accessing a column( we have already seen that)
# check for unique values
# Renaming Columns
# Deleting Columns
# Creating new Columns

In [62]:
# This function tells us all the columns present in the data frame

df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [65]:
# Since it is nothing but a dict we can also extract column names using keys

df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [68]:
# Checking for unique values and their frequency

df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Leba

In [69]:
# What if we want the counts of countries? we use nunique in that case.

df['country'].nunique()

142

In [71]:
# now checking frequency of countries

df['country'].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

In [74]:
# Difference between df['country'] vs df[['country']]

In [77]:
# This is not so good looking , because it is a series

df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [78]:
type(df['country'])

pandas.core.series.Series

In [79]:
# This is a little good looking , because it is a data frame

df[['country']]

country
0     Afghanistan
1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
...           ...
1699     Zimbabwe
1700     Zimbabwe
1701     Zimbabwe
1702     Zimbabwe
1703     Zimbabwe

[1704 rows x 1 columns]

# Assignments

In [88]:
'''
Which of these would be the correct way to create a dataframe?

a.

df = pd.DataFrame([[1, 2], ["Ram", "Shyam"], ["IT", "Ops"]], columns = ["emp_id", "name", "dept"])
b. 

df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])
c.

df = pd.DataFrame([1, "Ram", "IT"], columns = ["emp_id", "name", "dept"])
d.

df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})

'''

# Solution b and d

'\nWhich of these would be the correct way to create a dataframe?\n\na.\n\ndf = pd.DataFrame([[1, 2], ["Ram", "Shyam"], ["IT", "Ops"]], columns = ["emp_id", "name", "dept"])\nb. \n\ndf = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])\nc.\n\ndf = pd.DataFrame([1, "Ram", "IT"], columns = ["emp_id", "name", "dept"])\nd.\n\ndf = pd.DataFrame({\'emp_id\':[1, 2], \'name\': [\'Ram\', \'Shyam\'], \'dept\':[\'IT\', \'Ops\']})\n\n'

In [89]:
#b

df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])

In [90]:
df

emp_id   name dept
0       1    Ram   IT
1       2  Shyam  Ops

In [91]:
# d

df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})

In [92]:
df

emp_id   name dept
0       1    Ram   IT
1       2  Shyam  Ops